### ISSUE TITLE
path permission error on Mac-os

### ISSUE THREAD

**Issue by KRRT7** [JustRedTTG/moss-desktop#2]
```
python moss.py
Config file created. You can edit it manually if you want.
Cef is not installed or is not compatible with your python version.
2024-10-21 06:32:17.044 python[56581:430120] +[IMKClient subclass]: chose IMKClient_Legacy
2024-10-21 06:32:17.044 python[56581:430120] +[IMKInputSession subclass]: chose IMKInputSession_Legacy
Exception in thread Thread-1 (install_thread):
Traceback (most recent call last):
  File "/Users/krrt7/miniforge3/envs/nuitka_env/lib/python3.11/threading.py", line 1045, in _bootstrap_inner
    self.run()
  File "/Users/krrt7/miniforge3/envs/nuitka_env/lib/python3.11/threading.py", line 982, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/krrt7/Desktop/nuitka_testing/moss-desktop/gui/screens/installer.py", line 121, in install_thread
    os.makedirs(dest_path, exist_ok=True)
  File "<frozen os>", line 215, in makedirs
  File "<frozen os>", line 225, in makedirs
PermissionError: [Errno 13] Permission denied: '/Library/Application Support/Moss'
```

**Comment by RedTTG** [comment]
Moss shouldn't be accessing the app directories if running from source, it seems like you are running a binary compiled version of moss through nuitka
